apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: argocd-gitops-api:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: api-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10